/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) battery_nominal_constr_h_fun_jac_uxt_zt_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

static const casadi_int casadi_s0[3] = {2, 1, 1};
static const casadi_int casadi_s1[3] = {0, 1, 1};
static const casadi_int casadi_s2[3] = {1, 1, 1};
static const casadi_int casadi_s3[11] = 
  {4, 2, 0, 3, 6, 0, 1, 2,
  0, 1, 2};
static const casadi_int casadi_s4[3] = {2, 0, 1};

/* battery_nominal_constr_h_fun_jac_uxt_zt:(i0[2],i1[2],i2[0],i3)->(o0[2],o1[4x2,6nz],o2[2x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *rr, w00, w01, w02, w03, w04, w05, w06, w07, w08, w09, w10;
  casadi_real w11, w12, w13, w14, *w15=w+15, *w16=w+21;
  const casadi_real *cs;
  /* #0: @0 = input[0][0] */
  w00 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = 0.915692 */
  w01 = 9.1569199999999995e-01;
  /* #2: @2 = 1 */
  w02 = 1.;
  /* #3: @3 = 3681.88 */
  w03 = 3.6818750000000000e+03;
  /* #4: @4 = 0.001 */
  w04 = 1.0000000000000000e-03;
  /* #5: @5 = 3500 */
  w05 = 3500.;
  /* #6: @6 = 0.00668451 */
  w06 = 6.6845076098596048e-03;
  /* #7: @7 = 100 */
  w07 = 100.;
  /* #8: @8 = input[1][0] */
  w08 = arg[1] ? arg[1][0] : 0;
  /* #9: @8 = (@7*@8) */
  w08  = (w07*w08);
  /* #10: @8 = (@6*@8) */
  w08  = (w06*w08);
  /* #11: @8 = (@5*@8) */
  w08  = (w05*w08);
  /* #12: @4 = (@4+@8) */
  w04 += w08;
  /* #13: @3 = (@3/@4) */
  w03 /= w04;
  /* #14: @8 = (-@3) */
  w08 = (- w03 );
  /* #15: @8 = exp(@8) */
  w08 = exp( w08 );
  /* #16: @2 = (@2-@8) */
  w02 -= w08;
  /* #17: @1 = (@1/@2) */
  w01 /= w02;
  /* #18: @9 = 1000 */
  w09 = 1000.;
  /* #19: @10 = input[1][1] */
  w10 = arg[1] ? arg[1][1] : 0;
  /* #20: @10 = (@9*@10) */
  w10  = (w09*w10);
  /* #21: @11 = (@1*@10) */
  w11  = (w01*w10);
  /* #22: @11 = (@11/@4) */
  w11 /= w04;
  /* #23: @12 = (@0+@11) */
  w12  = (w00+w11);
  /* #24: output[0][0] = @12 */
  if (res[0]) res[0][0] = w12;
  /* #25: @12 = 0.919681 */
  w12 = 9.1968099999999997e-01;
  /* #26: @13 = (@12*@11) */
  w13  = (w12*w11);
  /* #27: @14 = (@13*@8) */
  w14  = (w13*w08);
  /* #28: @14 = (@14+@0) */
  w14 += w00;
  /* #29: output[0][1] = @14 */
  if (res[0]) res[0][1] = w14;
  /* #30: @15 = zeros(4x2,6nz) */
  casadi_clear(w15, 6);
  /* #31: @2 = (@1/@2) */
  w02  = (w01/w02);
  /* #32: @3 = (@3/@4) */
  w03 /= w04;
  /* #33: @16 = ones(4x1,2nz) */
  casadi_fill(w16, 2, 1.);
  /* #34: {@14, NULL, NULL, NULL} = vertsplit(@16) */
  w14 = w16[0];
  /* #35: @7 = (@7*@14) */
  w07 *= w14;
  /* #36: @6 = (@6*@7) */
  w06 *= w07;
  /* #37: @5 = (@5*@6) */
  w05 *= w06;
  /* #38: @3 = (@3*@5) */
  w03 *= w05;
  /* #39: @3 = (@8*@3) */
  w03  = (w08*w03);
  /* #40: @2 = (@2*@3) */
  w02 *= w03;
  /* #41: @10 = (@10*@2) */
  w10 *= w02;
  /* #42: @10 = (@10/@4) */
  w10 /= w04;
  /* #43: @11 = (@11/@4) */
  w11 /= w04;
  /* #44: @11 = (@11*@5) */
  w11 *= w05;
  /* #45: @10 = (@10-@11) */
  w10 -= w11;
  /* #46: @11 = (@12*@10) */
  w11  = (w12*w10);
  /* #47: @11 = (@8*@11) */
  w11  = (w08*w11);
  /* #48: @13 = (@13*@3) */
  w13 *= w03;
  /* #49: @11 = (@11+@13) */
  w11 += w13;
  /* #50: @16 = vertcat(@10, @11) */
  rr=w16;
  *rr++ = w10;
  *rr++ = w11;
  /* #51: (@15[:6:3] = @16) */
  for (rr=w15+0, cs=w16; rr!=w15+6; rr+=3) *rr = *cs++;
  /* #52: @10 = ones(4x1,1nz) */
  w10 = 1.;
  /* #53: {NULL, @11, NULL, NULL} = vertsplit(@10) */
  w11 = w10;
  /* #54: @9 = (@9*@11) */
  w09 *= w11;
  /* #55: @1 = (@1*@9) */
  w01 *= w09;
  /* #56: @1 = (@1/@4) */
  w01 /= w04;
  /* #57: @12 = (@12*@1) */
  w12 *= w01;
  /* #58: @8 = (@8*@12) */
  w08 *= w12;
  /* #59: @16 = vertcat(@1, @8) */
  rr=w16;
  *rr++ = w01;
  *rr++ = w08;
  /* #60: (@15[1:7:3] = @16) */
  for (rr=w15+1, cs=w16; rr!=w15+7; rr+=3) *rr = *cs++;
  /* #61: @1 = ones(4x1,1nz) */
  w01 = 1.;
  /* #62: {NULL, NULL, @8, NULL} = vertsplit(@1) */
  w08 = w01;
  /* #63: @16 = vertcat(@8, @8) */
  rr=w16;
  *rr++ = w08;
  *rr++ = w08;
  /* #64: (@15[2:8:3] = @16) */
  for (rr=w15+2, cs=w16; rr!=w15+8; rr+=3) *rr = *cs++;
  /* #65: output[1][0] = @15 */
  casadi_copy(w15, 6, res[1]);
  return 0;
}

CASADI_SYMBOL_EXPORT int battery_nominal_constr_h_fun_jac_uxt_zt(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int battery_nominal_constr_h_fun_jac_uxt_zt_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int battery_nominal_constr_h_fun_jac_uxt_zt_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void battery_nominal_constr_h_fun_jac_uxt_zt_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int battery_nominal_constr_h_fun_jac_uxt_zt_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void battery_nominal_constr_h_fun_jac_uxt_zt_release(int mem) {
}

CASADI_SYMBOL_EXPORT void battery_nominal_constr_h_fun_jac_uxt_zt_incref(void) {
}

CASADI_SYMBOL_EXPORT void battery_nominal_constr_h_fun_jac_uxt_zt_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int battery_nominal_constr_h_fun_jac_uxt_zt_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int battery_nominal_constr_h_fun_jac_uxt_zt_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real battery_nominal_constr_h_fun_jac_uxt_zt_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* battery_nominal_constr_h_fun_jac_uxt_zt_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* battery_nominal_constr_h_fun_jac_uxt_zt_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* battery_nominal_constr_h_fun_jac_uxt_zt_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* battery_nominal_constr_h_fun_jac_uxt_zt_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s3;
    case 2: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int battery_nominal_constr_h_fun_jac_uxt_zt_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 7;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 23;
  return 0;
}

CASADI_SYMBOL_EXPORT int battery_nominal_constr_h_fun_jac_uxt_zt_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 7*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 23*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
