/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) battery_nominal_expl_vde_forw_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_trans CASADI_PREFIX(trans)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

static const casadi_int casadi_s0[7] = {2, 2, 0, 1, 2, 0, 0};
static const casadi_int casadi_s1[7] = {2, 2, 0, 2, 2, 0, 1};
static const casadi_int casadi_s2[3] = {2, 1, 1};
static const casadi_int casadi_s3[3] = {2, 2, 1};
static const casadi_int casadi_s4[3] = {1, 1, 1};

/* battery_nominal_expl_vde_forw:(i0[2],i1[2x2],i2[2x2],i3[2],i4)->(o0[2],o1[2x2,2nz],o2[2x2,2nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real *rr, w00, w01, w02, w03, w04, w05, w06, w07, w08, w09, w10;
  casadi_real w11, w12, w13, w14, w15, w16, w17, w18, w19, w20, *w21=w+21, *w22=w+25;
  casadi_real *w23=w+27, *w24=w+29;
  const casadi_real *cs;
  /* #0: @0 = 3.99396e-06 */
  w00 = 3.9939559748427673e-06;
  /* #1: @1 = 1.024 */
  w01 = 1.0240000000000000e+00;
  /* #2: @2 = input[4][0] */
  w02 = arg[4] ? arg[4][0] : 0;
  /* #3: @3 = sq(@2) */
  w03 = casadi_sq( w02 );
  /* #4: @1 = (@1*@3) */
  w01 *= w03;
  /* #5: @3 = 3500 */
  w03 = 3500.;
  /* #6: @4 = 0.00668451 */
  w04 = 6.6845076098596048e-03;
  /* #7: @5 = 100 */
  w05 = 100.;
  /* #8: @6 = input[3][0] */
  w06 = arg[3] ? arg[3][0] : 0;
  /* #9: @6 = (@5*@6) */
  w06  = (w05*w06);
  /* #10: @6 = (@4*@6) */
  w06  = (w04*w06);
  /* #11: @6 = (@3*@6) */
  w06  = (w03*w06);
  /* #12: @7 = 0.919681 */
  w07 = 9.1968099999999997e-01;
  /* #13: @8 = 0.915692 */
  w08 = 9.1569199999999995e-01;
  /* #14: @9 = 1 */
  w09 = 1.;
  /* #15: @10 = 3681.88 */
  w10 = 3.6818750000000000e+03;
  /* #16: @11 = 0.001 */
  w11 = 1.0000000000000000e-03;
  /* #17: @11 = (@11+@6) */
  w11 += w06;
  /* #18: @10 = (@10/@11) */
  w10 /= w11;
  /* #19: @12 = (-@10) */
  w12 = (- w10 );
  /* #20: @12 = exp(@12) */
  w12 = exp( w12 );
  /* #21: @9 = (@9-@12) */
  w09 -= w12;
  /* #22: @8 = (@8/@9) */
  w08 /= w09;
  /* #23: @13 = 1000 */
  w13 = 1000.;
  /* #24: @14 = input[3][1] */
  w14 = arg[3] ? arg[3][1] : 0;
  /* #25: @14 = (@13*@14) */
  w14  = (w13*w14);
  /* #26: @15 = (@8*@14) */
  w15  = (w08*w14);
  /* #27: @15 = (@15/@11) */
  w15 /= w11;
  /* #28: @16 = (@7*@15) */
  w16  = (w07*w15);
  /* #29: @17 = (@16*@12) */
  w17  = (w16*w12);
  /* #30: @18 = input[0][0] */
  w18 = arg[0] ? arg[0][0] : 0;
  /* #31: @17 = (@17+@18) */
  w17 += w18;
  /* #32: @19 = (@18+@15) */
  w19  = (w18+w15);
  /* #33: @17 = (@17-@19) */
  w17 -= w19;
  /* #34: @19 = (@6*@17) */
  w19  = (w06*w17);
  /* #35: @1 = (@1-@19) */
  w01 -= w19;
  /* #36: @19 = 7.38325 */
  w19 = 7.3832500000000003e+00;
  /* #37: @20 = 292.15 */
  w20 = 2.9214999999999998e+02;
  /* #38: @20 = (@20-@18) */
  w20 -= w18;
  /* #39: @20 = (@19*@20) */
  w20  = (w19*w20);
  /* #40: @1 = (@1+@20) */
  w01 += w20;
  /* #41: @1 = (@0*@1) */
  w01  = (w00*w01);
  /* #42: output[0][0] = @1 */
  if (res[0]) res[0][0] = w01;
  /* #43: @1 = 100800 */
  w01 = 100800.;
  /* #44: @2 = (@2/@1) */
  w02 /= w01;
  /* #45: @2 = (-@2) */
  w02 = (- w02 );
  /* #46: output[0][1] = @2 */
  if (res[0]) res[0][1] = w02;
  /* #47: @21 = input[1][0] */
  casadi_copy(arg[1], 4, w21);
  /* #48: {@22, @23} = horzsplit(@21) */
  casadi_copy(w21, 2, w22);
  casadi_copy(w21+2, 2, w23);
  /* #49: {@2, NULL} = vertsplit(@22) */
  w02 = w22[0];
  /* #50: @2 = (@19*@2) */
  w02  = (w19*w02);
  /* #51: @2 = (@0*@2) */
  w02  = (w00*w02);
  /* #52: @2 = (-@2) */
  w02 = (- w02 );
  /* #53: output[1][0] = @2 */
  if (res[1]) res[1][0] = w02;
  /* #54: {@2, NULL} = vertsplit(@23) */
  w02 = w23[0];
  /* #55: @2 = (@19*@2) */
  w02  = (w19*w02);
  /* #56: @2 = (@0*@2) */
  w02  = (w00*w02);
  /* #57: @2 = (-@2) */
  w02 = (- w02 );
  /* #58: output[1][1] = @2 */
  if (res[1]) res[1][1] = w02;
  /* #59: @23 = zeros(2x2,2nz) */
  casadi_clear(w23, 2);
  /* #60: @2 = ones(2x1,1nz) */
  w02 = 1.;
  /* #61: {@1, NULL} = vertsplit(@2) */
  w01 = w02;
  /* #62: @5 = (@5*@1) */
  w05 *= w01;
  /* #63: @4 = (@4*@5) */
  w04 *= w05;
  /* #64: @3 = (@3*@4) */
  w03 *= w04;
  /* #65: @17 = (@17*@3) */
  w17 *= w03;
  /* #66: @9 = (@8/@9) */
  w09  = (w08/w09);
  /* #67: @10 = (@10/@11) */
  w10 /= w11;
  /* #68: @10 = (@10*@3) */
  w10 *= w03;
  /* #69: @10 = (@12*@10) */
  w10  = (w12*w10);
  /* #70: @9 = (@9*@10) */
  w09 *= w10;
  /* #71: @14 = (@14*@9) */
  w14 *= w09;
  /* #72: @14 = (@14/@11) */
  w14 /= w11;
  /* #73: @15 = (@15/@11) */
  w15 /= w11;
  /* #74: @15 = (@15*@3) */
  w15 *= w03;
  /* #75: @14 = (@14-@15) */
  w14 -= w15;
  /* #76: @15 = (@7*@14) */
  w15  = (w07*w14);
  /* #77: @15 = (@12*@15) */
  w15  = (w12*w15);
  /* #78: @16 = (@16*@10) */
  w16 *= w10;
  /* #79: @15 = (@15+@16) */
  w15 += w16;
  /* #80: @15 = (@15-@14) */
  w15 -= w14;
  /* #81: @15 = (@6*@15) */
  w15  = (w06*w15);
  /* #82: @17 = (@17+@15) */
  w17 += w15;
  /* #83: @17 = (@0*@17) */
  w17  = (w00*w17);
  /* #84: @17 = (-@17) */
  w17 = (- w17 );
  /* #85: (@23[0] = @17) */
  for (rr=w23+0, cs=(&w17); rr!=w23+1; rr+=1) *rr = *cs++;
  /* #86: @17 = ones(2x1,1nz) */
  w17 = 1.;
  /* #87: {NULL, @15} = vertsplit(@17) */
  w15 = w17;
  /* #88: @13 = (@13*@15) */
  w13 *= w15;
  /* #89: @8 = (@8*@13) */
  w08 *= w13;
  /* #90: @8 = (@8/@11) */
  w08 /= w11;
  /* #91: @7 = (@7*@8) */
  w07 *= w08;
  /* #92: @12 = (@12*@7) */
  w12 *= w07;
  /* #93: @12 = (@12-@8) */
  w12 -= w08;
  /* #94: @6 = (@6*@12) */
  w06 *= w12;
  /* #95: @6 = (@0*@6) */
  w06  = (w00*w06);
  /* #96: @6 = (-@6) */
  w06 = (- w06 );
  /* #97: (@23[1] = @6) */
  for (rr=w23+1, cs=(&w06); rr!=w23+2; rr+=1) *rr = *cs++;
  /* #98: @22 = @23' */
  casadi_trans(w23,casadi_s1, w22, casadi_s0, iw);
  /* #99: @21 = input[2][0] */
  casadi_copy(arg[2], 4, w21);
  /* #100: {@23, @24} = horzsplit(@21) */
  casadi_copy(w21, 2, w23);
  casadi_copy(w21+2, 2, w24);
  /* #101: {@6, NULL} = vertsplit(@23) */
  w06 = w23[0];
  /* #102: @6 = (@19*@6) */
  w06  = (w19*w06);
  /* #103: @6 = (@0*@6) */
  w06  = (w00*w06);
  /* #104: @6 = (-@6) */
  w06 = (- w06 );
  /* #105: @25 = 00 */
  /* #106: @12 = vertcat(@6, @25) */
  rr=(&w12);
  *rr++ = w06;
  /* #107: {@6, NULL} = vertsplit(@24) */
  w06 = w24[0];
  /* #108: @19 = (@19*@6) */
  w19 *= w06;
  /* #109: @0 = (@0*@19) */
  w00 *= w19;
  /* #110: @0 = (-@0) */
  w00 = (- w00 );
  /* #111: @19 = vertcat(@0, @25) */
  rr=(&w19);
  *rr++ = w00;
  /* #112: @24 = horzcat(@12, @19) */
  rr=w24;
  *rr++ = w12;
  *rr++ = w19;
  /* #113: @22 = (@22+@24) */
  for (i=0, rr=w22, cs=w24; i<2; ++i) (*rr++) += (*cs++);
  /* #114: output[2][0] = @22 */
  casadi_copy(w22, 2, res[2]);
  return 0;
}

CASADI_SYMBOL_EXPORT int battery_nominal_expl_vde_forw(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int battery_nominal_expl_vde_forw_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int battery_nominal_expl_vde_forw_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void battery_nominal_expl_vde_forw_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int battery_nominal_expl_vde_forw_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void battery_nominal_expl_vde_forw_release(int mem) {
}

CASADI_SYMBOL_EXPORT void battery_nominal_expl_vde_forw_incref(void) {
}

CASADI_SYMBOL_EXPORT void battery_nominal_expl_vde_forw_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int battery_nominal_expl_vde_forw_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int battery_nominal_expl_vde_forw_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real battery_nominal_expl_vde_forw_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* battery_nominal_expl_vde_forw_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* battery_nominal_expl_vde_forw_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* battery_nominal_expl_vde_forw_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    case 1: return casadi_s3;
    case 2: return casadi_s3;
    case 3: return casadi_s2;
    case 4: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* battery_nominal_expl_vde_forw_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    case 1: return casadi_s0;
    case 2: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int battery_nominal_expl_vde_forw_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7;
  if (sz_res) *sz_res = 5;
  if (sz_iw) *sz_iw = 3;
  if (sz_w) *sz_w = 31;
  return 0;
}

CASADI_SYMBOL_EXPORT int battery_nominal_expl_vde_forw_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 5*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 3*sizeof(casadi_int);
  if (sz_w) *sz_w = 31*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
