/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) battery_nominal_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

static const casadi_int casadi_s0[3] = {2, 1, 1};
static const casadi_int casadi_s1[3] = {1, 1, 1};
static const casadi_int casadi_s2[7] = {4, 1, 0, 3, 0, 2, 3};

/* battery_nominal_expl_vde_adj:(i0[2],i1[2],i2[2],i3)->(o0[4x1,3nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w00, w01, *w02=w+2, w03, w04, w05, w06, w07, w08, w09, w10, w11;
  casadi_real w12, w13, w14, w15, w16, w17;
  /* #0: @0 = 7.38325 */
  w00 = 7.3832500000000003e+00;
  /* #1: @1 = 3.99396e-06 */
  w01 = 3.9939559748427673e-06;
  /* #2: @2 = input[1][0] */
  casadi_copy(arg[1], 2, w02);
  /* #3: {@3, NULL} = vertsplit(@2) */
  w03 = w02[0];
  /* #4: @1 = (@1*@3) */
  w01 *= w03;
  /* #5: @0 = (@0*@1) */
  w00 *= w01;
  /* #6: @0 = (-@0) */
  w00 = (- w00 );
  /* #7: output[0][0] = @0 */
  if (res[0]) res[0][0] = w00;
  /* #8: @0 = 100 */
  w00 = 100.;
  /* #9: @3 = 0.00668451 */
  w03 = 6.6845076098596048e-03;
  /* #10: @4 = 3500 */
  w04 = 3500.;
  /* #11: @5 = 3681.88 */
  w05 = 3.6818750000000000e+03;
  /* #12: @6 = 0.001 */
  w06 = 1.0000000000000000e-03;
  /* #13: @7 = input[2][0] */
  w07 = arg[2] ? arg[2][0] : 0;
  /* #14: @7 = (@0*@7) */
  w07  = (w00*w07);
  /* #15: @7 = (@3*@7) */
  w07  = (w03*w07);
  /* #16: @7 = (@4*@7) */
  w07  = (w04*w07);
  /* #17: @6 = (@6+@7) */
  w06 += w07;
  /* #18: @5 = (@5/@6) */
  w05 /= w06;
  /* #19: @8 = (@5/@6) */
  w08  = (w05/w06);
  /* #20: @5 = (-@5) */
  w05 = (- w05 );
  /* #21: @5 = exp(@5) */
  w05 = exp( w05 );
  /* #22: @9 = 0.919681 */
  w09 = 9.1968099999999997e-01;
  /* #23: @10 = 0.915692 */
  w10 = 9.1569199999999995e-01;
  /* #24: @11 = 1 */
  w11 = 1.;
  /* #25: @11 = (@11-@5) */
  w11 -= w05;
  /* #26: @10 = (@10/@11) */
  w10 /= w11;
  /* #27: @12 = 1000 */
  w12 = 1000.;
  /* #28: @13 = input[2][1] */
  w13 = arg[2] ? arg[2][1] : 0;
  /* #29: @13 = (@12*@13) */
  w13  = (w12*w13);
  /* #30: @14 = (@10*@13) */
  w14  = (w10*w13);
  /* #31: @14 = (@14/@6) */
  w14 /= w06;
  /* #32: @15 = (@9*@14) */
  w15  = (w09*w14);
  /* #33: @7 = (@7*@1) */
  w07 *= w01;
  /* #34: @16 = (@15*@7) */
  w16  = (w15*w07);
  /* #35: @16 = (@5*@16) */
  w16  = (w05*w16);
  /* #36: @11 = (@10/@11) */
  w11  = (w10/w11);
  /* #37: @17 = (@5*@7) */
  w17  = (w05*w07);
  /* #38: @9 = (@9*@17) */
  w09 *= w17;
  /* #39: @7 = (@7-@9) */
  w07 -= w09;
  /* #40: @9 = (@7/@6) */
  w09  = (w07/w06);
  /* #41: @13 = (@13*@9) */
  w13 *= w09;
  /* #42: @11 = (@11*@13) */
  w11 *= w13;
  /* #43: @11 = (@5*@11) */
  w11  = (w05*w11);
  /* #44: @16 = (@16-@11) */
  w16 -= w11;
  /* #45: @8 = (@8*@16) */
  w08 *= w16;
  /* #46: @8 = (@4*@8) */
  w08  = (w04*w08);
  /* #47: @8 = (-@8) */
  w08 = (- w08 );
  /* #48: @6 = (@14/@6) */
  w06  = (w14/w06);
  /* #49: @6 = (@6*@7) */
  w06 *= w07;
  /* #50: @6 = (@4*@6) */
  w06  = (w04*w06);
  /* #51: @8 = (@8-@6) */
  w08 -= w06;
  /* #52: @15 = (@15*@5) */
  w15 *= w05;
  /* #53: @5 = input[0][0] */
  w05 = arg[0] ? arg[0][0] : 0;
  /* #54: @15 = (@15+@5) */
  w15 += w05;
  /* #55: @5 = (@5+@14) */
  w05 += w14;
  /* #56: @15 = (@15-@5) */
  w15 -= w05;
  /* #57: @15 = (@15*@1) */
  w15 *= w01;
  /* #58: @4 = (@4*@15) */
  w04 *= w15;
  /* #59: @8 = (@8-@4) */
  w08 -= w04;
  /* #60: @3 = (@3*@8) */
  w03 *= w08;
  /* #61: @0 = (@0*@3) */
  w00 *= w03;
  /* #62: output[0][1] = @0 */
  if (res[0]) res[0][1] = w00;
  /* #63: @10 = (@10*@9) */
  w10 *= w09;
  /* #64: @12 = (@12*@10) */
  w12 *= w10;
  /* #65: output[0][2] = @12 */
  if (res[0]) res[0][2] = w12;
  return 0;
}

CASADI_SYMBOL_EXPORT int battery_nominal_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int battery_nominal_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int battery_nominal_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void battery_nominal_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int battery_nominal_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void battery_nominal_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void battery_nominal_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void battery_nominal_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int battery_nominal_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int battery_nominal_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real battery_nominal_expl_vde_adj_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* battery_nominal_expl_vde_adj_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* battery_nominal_expl_vde_adj_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* battery_nominal_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s0;
    case 3: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* battery_nominal_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int battery_nominal_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 19;
  return 0;
}

CASADI_SYMBOL_EXPORT int battery_nominal_expl_vde_adj_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 3*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 19*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
