/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) battery_nominal_expl_ode_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {2, 1, 1};
static const casadi_int casadi_s1[3] = {1, 1, 1};

/* battery_nominal_expl_ode_fun:(i0[2],i1[2],i2)->(o0[2]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1, w2, w3, w4, w5, w6, w7, w8, w9;
  /* #0: @0 = 3.99396e-06 */
  w0 = 3.9939559748427673e-06;
  /* #1: @1 = 1.024 */
  w1 = 1.0240000000000000e+00;
  /* #2: @2 = input[2][0] */
  w2 = arg[2] ? arg[2][0] : 0;
  /* #3: @3 = sq(@2) */
  w3 = casadi_sq( w2 );
  /* #4: @1 = (@1*@3) */
  w1 *= w3;
  /* #5: @3 = 3500 */
  w3 = 3500.;
  /* #6: @4 = 0.00668451 */
  w4 = 6.6845076098596048e-03;
  /* #7: @5 = 100 */
  w5 = 100.;
  /* #8: @6 = input[1][0] */
  w6 = arg[1] ? arg[1][0] : 0;
  /* #9: @5 = (@5*@6) */
  w5 *= w6;
  /* #10: @4 = (@4*@5) */
  w4 *= w5;
  /* #11: @3 = (@3*@4) */
  w3 *= w4;
  /* #12: @4 = 0.919681 */
  w4 = 9.1968099999999997e-01;
  /* #13: @5 = 0.915692 */
  w5 = 9.1569199999999995e-01;
  /* #14: @6 = 1 */
  w6 = 1.;
  /* #15: @7 = 3681.88 */
  w7 = 3.6818750000000000e+03;
  /* #16: @8 = 0.001 */
  w8 = 1.0000000000000000e-03;
  /* #17: @8 = (@8+@3) */
  w8 += w3;
  /* #18: @7 = (@7/@8) */
  w7 /= w8;
  /* #19: @7 = (-@7) */
  w7 = (- w7 );
  /* #20: @7 = exp(@7) */
  w7 = exp( w7 );
  /* #21: @6 = (@6-@7) */
  w6 -= w7;
  /* #22: @5 = (@5/@6) */
  w5 /= w6;
  /* #23: @6 = 1000 */
  w6 = 1000.;
  /* #24: @9 = input[1][1] */
  w9 = arg[1] ? arg[1][1] : 0;
  /* #25: @6 = (@6*@9) */
  w6 *= w9;
  /* #26: @5 = (@5*@6) */
  w5 *= w6;
  /* #27: @5 = (@5/@8) */
  w5 /= w8;
  /* #28: @4 = (@4*@5) */
  w4 *= w5;
  /* #29: @4 = (@4*@7) */
  w4 *= w7;
  /* #30: @7 = input[0][0] */
  w7 = arg[0] ? arg[0][0] : 0;
  /* #31: @4 = (@4+@7) */
  w4 += w7;
  /* #32: @5 = (@7+@5) */
  w5  = (w7+w5);
  /* #33: @4 = (@4-@5) */
  w4 -= w5;
  /* #34: @3 = (@3*@4) */
  w3 *= w4;
  /* #35: @1 = (@1-@3) */
  w1 -= w3;
  /* #36: @3 = 7.38325 */
  w3 = 7.3832500000000003e+00;
  /* #37: @4 = 263.15 */
  w4 = 2.6314999999999998e+02;
  /* #38: @4 = (@4-@7) */
  w4 -= w7;
  /* #39: @3 = (@3*@4) */
  w3 *= w4;
  /* #40: @1 = (@1+@3) */
  w1 += w3;
  /* #41: @0 = (@0*@1) */
  w0 *= w1;
  /* #42: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  /* #43: @0 = 100800 */
  w0 = 100800.;
  /* #44: @2 = (@2/@0) */
  w2 /= w0;
  /* #45: @2 = (-@2) */
  w2 = (- w2 );
  /* #46: output[0][1] = @2 */
  if (res[0]) res[0][1] = w2;
  return 0;
}

CASADI_SYMBOL_EXPORT int battery_nominal_expl_ode_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int battery_nominal_expl_ode_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int battery_nominal_expl_ode_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void battery_nominal_expl_ode_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int battery_nominal_expl_ode_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void battery_nominal_expl_ode_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void battery_nominal_expl_ode_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void battery_nominal_expl_ode_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int battery_nominal_expl_ode_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int battery_nominal_expl_ode_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real battery_nominal_expl_ode_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* battery_nominal_expl_ode_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* battery_nominal_expl_ode_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* battery_nominal_expl_ode_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* battery_nominal_expl_ode_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int battery_nominal_expl_ode_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 10;
  return 0;
}

CASADI_SYMBOL_EXPORT int battery_nominal_expl_ode_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 10*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
